/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ControlCard.KKTableRenderer;
import MyClasses.TableOutputHeaderMouseListener;
import com.kprm.materialmanager.AtestIndicatorManager;
import com.kprm.materialmanager.AtestManager;
import com.kprm.materialmanager.BomManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author wakan
 */
public class FrmAtestIndicator extends javax.swing.JFrame {

  /**
   * Tryb pracy: 0 - przyporządkowanie atestu z poziomu materiału w głównym
   * oknie 1 - przyporządkowanie atestu do wielu materiałów z poziomu CertToMany
   */
  private int mode = 0;
  private JTable tblAtests;
  private JTable tblBom;
  private JTree treeKontrakty;

  /**
   * Creates new form FrmAtestIndicator
   */
  public FrmAtestIndicator() {
    initComponents();
    createTableHeadersClickListeners();

    DefaultTableCellRenderer renderer = new KKTableRenderer();

    tblOutput.setDefaultRenderer(Object.class, renderer);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel6 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    tfFilter = new javax.swing.JTextField();
    jScrollPane3 = new javax.swing.JScrollPane();
    treeMaterialy = new javax.swing.JTree();
    jPanel5 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblOutput = new javax.swing.JTable(){
      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return false;
      }
    };
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfAtest = new javax.swing.JTextField();
    tfMaterial = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();

    setTitle("Przyporządkuj atest");
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/product.png")).getImage());
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });

    jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
    jSplitPane1.setDividerLocation(320);

    jPanel6.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        jPanel6ComponentShown(evt);
      }
    });

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtr", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel3.setText("Nazwa:");

    tfFilter.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
    tfFilter.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tfFilterKeyReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfFilter)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addContainerGap())
    );

    treeMaterialy.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
    javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Materiały");
    treeMaterialy.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
    treeMaterialy.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        treeMaterialyMousePressed(evt);
      }
    });
    jScrollPane3.setViewportView(treeMaterialy);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jSplitPane1.setLeftComponent(jPanel6);

    tblOutput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    tblOutput.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nazwa", "Materiał", "Nr WZ", "Nr Zamówienia", "Data dodania"
      }
    ));
    jScrollPane1.setViewportView(tblOutput);
    if (tblOutput.getColumnModel().getColumnCount() > 0) {
      tblOutput.getColumnModel().getColumn(3).setMinWidth(100);
      tblOutput.getColumnModel().getColumn(3).setMaxWidth(300);
      tblOutput.getColumnModel().getColumn(4).setMinWidth(100);
      tblOutput.getColumnModel().getColumn(4).setMaxWidth(300);
    }

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Szukaj", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setText("Nazwa atestu:");

    tfAtest.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
    tfAtest.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tfAtestKeyReleased(evt);
      }
    });

    tfMaterial.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
    tfMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tfMaterialKeyReleased(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel2.setText("Materiał:");

    jButton2.setBackground(new java.awt.Color(0, 153, 0));
    jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton2.setText("SZUKAJ");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfAtest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
        .addComponent(jButton2)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(tfAtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(tfMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2))
        .addContainerGap(16, Short.MAX_VALUE))
    );

    jButton1.setBackground(new java.awt.Color(0, 153, 0));
    jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton1.setText("WYBIERZ ATEST");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButton1)))
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap())
    );

    jSplitPane1.setRightComponent(jPanel5);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jSplitPane1)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Tworzy nasłuch w którym program wykrywa kliknięcie w nagłówku tabeli
   * wyników poszukiwania atestów.
   */
  private void createTableHeadersClickListeners() {
    JTableHeader headTblAtesty = tblOutput.getTableHeader();
    headTblAtesty.addMouseListener(new TableOutputHeaderMouseListener(tblOutput));
  }

    private void tfAtestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAtestKeyReleased
      // TODO add your handling code here:

      int key = evt.getKeyCode();
      if (evt.getSource() == tfAtest) {
        if (key == KeyEvent.VK_ENTER) {
          AtestIndicatorManager.getInstance().searchCert(tfAtest.getText(),
                  tfMaterial.getText(), tblOutput);
        }
      }

//        AtestIndicatorManager.getInstance().searchCert(tfAtest.getText(),
//                tfMaterial.getText(), tblOutput);
    }//GEN-LAST:event_tfAtestKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
      if (this.mode == 0) {
        AtestIndicatorManager.getInstance().assignCert(tblOutput, tblAtests, tblBom);

        BomManager.getInstance().refreshAtestTable(
                tblAtests, BomManager.getInstance().getBomMaterials()[BomManager.getInstance().getSelectedBomMaterial()].getId());
        BomManager.getInstance().importBomFromDB(treeKontrakty, tblBom);

        this.setVisible(false);
      } else {
        AtestIndicatorManager.getInstance().assignCert(tblOutput, tblBom);
        this.setVisible(false);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfMaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMaterialKeyReleased
      // TODO add your handling code here:
      int key = evt.getKeyCode();
      if (evt.getSource() == tfMaterial) {
        if (key == KeyEvent.VK_ENTER) {
          AtestIndicatorManager.getInstance().searchCert(tfAtest.getText(),
                  tfMaterial.getText(), tblOutput);
        }
      }
//        AtestIndicatorManager.getInstance().searchCert(tfAtest.getText(),
//                tfMaterial.getText(), tblOutput);
    }//GEN-LAST:event_tfMaterialKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      AtestIndicatorManager.getInstance().searchCert(tfAtest.getText(),
              tfMaterial.getText(), tblOutput);
    }//GEN-LAST:event_jButton2ActionPerformed

  private void treeMaterialyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMaterialyMousePressed
    //AtestManager.getInstance().readCerts(tblAtesty, treeMaterialy, 0, null);

    DefaultMutableTreeNode selectedNode = 
            (DefaultMutableTreeNode) treeMaterialy.getLastSelectedPathComponent();
    
    AtestIndicatorManager.getInstance().searchCert("",
              selectedNode.toString(), tblOutput);
  }//GEN-LAST:event_treeMaterialyMousePressed

  private void jPanel6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel6ComponentShown
    // TODO add your handling code here:
    try {
      AtestManager.getInstance().readMaterialsFromDB(treeMaterialy, null);
    } catch (SQLException ex) {
      Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jPanel6ComponentShown

  private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    // TODO add your handling code here:
    try {
      AtestManager.getInstance().readMaterialsFromDB(treeMaterialy, null);
    } catch (SQLException ex) {
      Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_formComponentShown

  private void tfFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFilterKeyReleased
    // TODO add your handling code here:
    //((DefaultTableModel) tblAtesty.getModel()).setRowCount(0);
      try {
        // TODO add your handling code here:
        AtestManager.getInstance().readMaterialsFromDB(treeMaterialy, tfFilter.getText().trim());
      } catch (SQLException ex) {
        Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
      }
  }//GEN-LAST:event_tfFilterKeyReleased

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmAtestIndicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new FrmAtestIndicator().setVisible(true);
    });
  }

  /**
   *
   * @param tblBom Tabela z bomami.
   * @param tblAtest Tabela w której znajdują się atesty w zakładce materiały.
   * @param treeKontrakty Drzewko kontraktów.
   */
  public void show(JTable tblBom, JTable tblAtest, JTree treeKontrakty) {
    this.mode = 0;
    this.tblAtests = tblAtest;
    this.tblBom = tblBom;
    this.treeKontrakty = treeKontrakty;
    super.show(); //To change body of generated methods, choose Tools | Templates.
  }

  /**
   * Uruchomiony z poziomu przyporządkowania atestu do wielu materiałów.
   *
   * @param tblBomMaterials Tabela z materiałami z bomów
   * @param treeKontrakty Drzewko z kontraktami.
   */
  public void show(JTable tblBomMaterials, JTree treeKontrakty) {
    this.mode = 1;
    this.tblBom = tblBomMaterials;
    this.treeKontrakty = treeKontrakty;
    super.show();
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTable tblOutput;
  private javax.swing.JTextField tfAtest;
  private javax.swing.JTextField tfFilter;
  private javax.swing.JTextField tfMaterial;
  private javax.swing.JTree treeMaterialy;
  // End of variables declaration//GEN-END:variables
}
