/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlCard;

import com.kprm.materialmanager.SettingsManager;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wakan
 */
public class FrmKKCreator extends javax.swing.JFrame {

  /**
   * Creates new form FrmKKCreator
   */
  public FrmKKCreator() {
    initComponents();

    try {
      KKCreatorManager.getInstance().openFileAndFillTable(tblKontrakty, this);
    } catch (IOException ex) {
      Logger.getLogger(KKCreatorManager.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    tfContractNumber = new javax.swing.JTextField();
    tfObjectNumber = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblKontrakty = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    cbBearingKind = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    tfA = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    tfH = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    tfBottomPlate = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    tfDestPath = new javax.swing.JTextField();
    btnGenerateCard = new javax.swing.JButton();
    btnChooseFolder = new javax.swing.JButton();

    setTitle("Kreator Karty kontroli dla łożysk elastomerowych");
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/product.png")).getImage());

    jLabel3.setText("Filtr");

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setText("Kontrakt:");

    tfContractNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    tfContractNumber.setName("tfKontrakt"); // NOI18N
    tfContractNumber.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tfContractNumberKeyReleased(evt);
      }
    });

    tfObjectNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    tfObjectNumber.setName("tfObiekt"); // NOI18N
    tfObjectNumber.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tfObjectNumberKeyReleased(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel2.setText("Obiekt:");

    tblKontrakty.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    tblKontrakty.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Kontrakt", "Numer seryjny", "Symbol", "Typ", "Rodzaj", "Obiekt", "Pozycja", "Nośność pionowa", "Zakres przesuwów"
      }
    ));
    tblKontrakty.setRowHeight(20);
    tblKontrakty.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        tblKontraktyMousePressed(evt);
      }
    });
    jScrollPane1.setViewportView(tblKontrakty);

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    cbBearingKind.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    cbBearingKind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednokierunkowe", "Stałe", "Wielokierunkowe", "Wielokierunkowe oblachowane", "(!) TYP NIEZNANY (!)" }));

    jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel8.setText("Rodzaj łożyska:");

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel4.setText("Szerokość (A):");

    tfA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel5.setText("Wysokość (H):");

    tfH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel6.setText("Wymiar płyty dolnej:");

    tfBottomPlate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel8)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cbBearingKind, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(38, 38, 38)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(48, 48, 48)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfBottomPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbBearingKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(tfBottomPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel7.setText("Ścieżka zapisu Kart:");

    tfDestPath.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    btnGenerateCard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    btnGenerateCard.setText("GENERUJ KARTĘ");
    btnGenerateCard.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGenerateCardActionPerformed(evt);
      }
    });

    btnChooseFolder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    btnChooseFolder.setText("Wybierz folder");
    btnChooseFolder.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnChooseFolderActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfDestPath, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnChooseFolder)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnGenerateCard)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGenerateCard)
          .addComponent(tfDestPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7)
          .addComponent(btnChooseFolder))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfObjectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(tfContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(tfObjectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void tfContractNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfContractNumberKeyReleased
    // TODO add your handling code here:
    KKCreatorManager.getInstance().filterTable(tfContractNumber.getText(), tfObjectNumber.getText(), tblKontrakty);

  }//GEN-LAST:event_tfContractNumberKeyReleased

  private void tfObjectNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfObjectNumberKeyReleased
    // TODO add your handling code here:
    KKCreatorManager.getInstance().filterTable(tfContractNumber.getText(), tfObjectNumber.getText(), tblKontrakty);
  }//GEN-LAST:event_tfObjectNumberKeyReleased

  private void btnGenerateCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateCardActionPerformed

    try {
      System.out.println("Zaznaczony wiersz: " + tblKontrakty.getSelectedRow());
      if (tblKontrakty.getSelectedRow() != -1) {

        switch (cbBearingKind.getSelectedIndex()) {
          case 0: // Łożysko jednokierunkowe
            KKCreatorManager.getInstance().modifyKKexcelOneWayBaring(
                    tblKontrakty, tfA.getText(), tfH.getText(),
                    tfBottomPlate.getText(), tfDestPath.getText());
            break;
          case 1: // Łożysko stałe
            KKCreatorManager.getInstance().modifyKKexcelOneWayBaring(
                    tblKontrakty, tfA.getText(), tfH.getText(),
                    tfBottomPlate.getText(), tfDestPath.getText());
            break;
          case 2: // Łożysko wielokierunkowe
            KKCreatorManager.getInstance().modifyKKexcelManyWayBearing(
                    tblKontrakty, tfDestPath.getText());
            break;
          case 3: // Łożysko wielokierunkowe oblachowane
            KKCreatorManager.getInstance().modifyKKexcelOneWayBaring(
                    tblKontrakty, tfA.getText(), tfH.getText(),
                    tfBottomPlate.getText(), tfDestPath.getText());
            break;
          case 4: // Nieznany rodzaj łożyska
            JOptionPane.showMessageDialog(null, "Nieznany rodzaj łożyska", "Nie można wygenerować karty", JOptionPane.ERROR_MESSAGE);
            break;
        }
      } else {
        JOptionPane.showMessageDialog(null, "Zaznacz łożysko w tabeli", "Błąd", JOptionPane.ERROR_MESSAGE);
      }
    } catch (IOException ex) {
      Logger.getLogger(FrmKKCreator.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, ex, "Błąd", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException ex) {
      JOptionPane.showMessageDialog(null, "Wprowadź poprawne wymiary A, H, Płyty dolnej", "Błąd", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btnGenerateCardActionPerformed

  private void tblKontraktyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKontraktyMousePressed
    // TODO add your handling code here:
    System.out.println(cbBearingKind.getSelectedItem().toString());

    DefaultTableModel model = (DefaultTableModel) tblKontrakty.getModel();

    switch ((model.getValueAt(tblKontrakty.getSelectedRow(), 4)).toString()) {
      case "Jednokierunkowe":
        cbBearingKind.setSelectedIndex(0);
        break;
      case "Stałe":
        cbBearingKind.setSelectedIndex(1);
        break;
      case "Wielokierunkowe":
        cbBearingKind.setSelectedIndex(2);
        break;
      case "Wielokierunkowe oblachowane":
        cbBearingKind.setSelectedIndex(3);
        break;
      default:
        cbBearingKind.setSelectedIndex(4);

    }

    System.out.println("Rodzaj: " + model.getValueAt(tblKontrakty.getSelectedRow(), 4));

  }//GEN-LAST:event_tblKontraktyMousePressed

  private void btnChooseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFolderActionPerformed
    // TODO add your handling code here:
    SettingsManager.getInstance().setupControlCardSavePath(tfDestPath);    
  }//GEN-LAST:event_btnChooseFolderActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmKKCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmKKCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmKKCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmKKCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
          new FrmKKCreator().setVisible(true);
        
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnChooseFolder;
  private javax.swing.JButton btnGenerateCard;
  private javax.swing.JComboBox<String> cbBearingKind;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblKontrakty;
  private javax.swing.JTextField tfA;
  private javax.swing.JTextField tfBottomPlate;
  private javax.swing.JTextField tfContractNumber;
  private javax.swing.JTextField tfDestPath;
  private javax.swing.JTextField tfH;
  private javax.swing.JTextField tfObjectNumber;
  // End of variables declaration//GEN-END:variables
}
