package MyClasses;

/**
 * Tryby sortowania
 * @author Łukasz Wawrzyniak
 */
public enum SortModes {
    ATEST_NAZWA_UP, ATEST_NAZWA_DOWN, ATEST_WZ_UP, ATEST_WZ_DOWN, ATEST_ZP_UP,
    ATEST_ZP_DOWN, ATEST_DATA_UP, ATEST_DATA_DOWN, ATEST_DOSTAWCA_UP, 
    ATEST_DOSTAWCA_DOWN, ATEST_NRZAM_UP, ATEST_NRZAM_DOWN, ATEST_PKD_UP,
    ATEST_PKD_DOWN, ATEST_NAZWA_MATERIALU_UP, ATEST_NAZWA_MATERIALU_DOWN
}
